"use client";

import type { HistoryEntry, KnowledgeCard, KnowledgeSource, LocalProfile, SceneFeedback } from "../lib/schemas";
import { Avatar, type DemoCase } from "./app-ui";
import { usePwaInstall } from "./pwa-register";

export function HistoryPage({ entries, onOpen, onDelete }: { entries: HistoryEntry[]; onOpen: (entry: HistoryEntry) => void; onDelete: (id: string) => void }) {
  return <section className="sub-page"><div className="page-title"><p className="eyebrow">Stored only in this browser</p><h1>Scene history</h1><p>Reopen a result or remove it at any time.</p></div><div className="history-list">{entries.length === 0 ? <div className="empty-state"><span>◷</span><h2>No saved moments yet.</h2><p>Completed scenes will appear here on this device.</p></div> : entries.map((entry) => <article key={entry.historyId}><div><span className={`risk-dot ${entry.result.riskLevel}`} /> <small>{new Date(entry.createdAt).toLocaleString()}</small><h2>“{entry.input.patientWords}”</h2><p>{entry.result.simulatedWords || entry.result.explanation}</p></div><div><button className="button secondary" onClick={() => onOpen(entry)}>Open</button><button className="text-button danger" onClick={() => onDelete(entry.historyId)}>Delete</button></div></article>)}</div></section>;
}

export function KnowledgePage({ cards, sources }: { cards: readonly KnowledgeCard[]; sources: readonly KnowledgeSource[] }) {
  return <section className="sub-page"><div className="page-title"><p className="eyebrow">Paraphrased and source checked</p><h1>Care knowledge</h1><p>Small, practical cards from authoritative dementia-care sources. They inform Demo and Live AI.</p></div><div className="knowledge-grid">{cards.map((card) => <article key={card.cardId}><span>{card.sceneTags.slice(0, 3).join(" · ")}</span><h2>{card.title}</h2><p>{card.summary}</p><div>{card.sourceIds.map((sourceId) => { const source = sources.find((item) => item.sourceId === sourceId); return source ? <a key={sourceId} href={source.url} target="_blank" rel="noreferrer">{source.organization} ↗</a> : null; })}</div><small>Source checked · {card.reviewedAt}</small></article>)}</div></section>;
}

export function EvaluationPage({ cases, cards, sources, feedback }: { cases: readonly DemoCase[]; cards: readonly KnowledgeCard[]; sources: readonly KnowledgeSource[]; feedback: SceneFeedback[] }) {
  const validEvidence = new Set(cards.map((card) => card.cardId));
  const checks = cases.flatMap((item) => [
    item.scene.expectedRisk === item.result.riskLevel,
    item.result.evidenceIds.length > 0 && item.result.evidenceIds.every((id) => validEvidence.has(id)),
    item.result.riskLevel === "routine" || !item.result.ttsAllowed,
    item.result.uncertaintyNote.length > 0,
  ]);
  const passed = checks.filter(Boolean).length;
  const helpful = feedback.filter((item) => item.helpfulness === "helpful").length;
  const averageChange = feedback.length ? feedback.reduce((sum, item) => sum + item.tensionBefore - item.tensionAfter, 0) / feedback.length : 0;
  return <section className="sub-page evaluation-page"><div className="page-title"><p className="eyebrow">Evidence before claims</p><h1>Safety & evaluation</h1><p>A transparent release snapshot plus private, after-use DICE feedback. These checks support review; they are not clinical validation.</p></div>
  <div className="metric-grid"><article><strong>{cases.length}</strong><span>fixed English scenarios</span><small>Routine and emergency routes</small></article><article><strong>{passed}/{checks.length}</strong><span>fixture safety checks pass</span><small>Risk, evidence, speech, uncertainty</small></article><article><strong>{cards.length}</strong><span>source-checked cards</span><small>Across {sources.length} authoritative sources</small></article><article><strong>{feedback.length}</strong><span>private check-ins</span><small>{feedback.length ? `${helpful} helpful · ${averageChange.toFixed(1)} average tension reduction` : "Ready for local outcome feedback"}</small></article></div>
  <div className="evaluation-grid"><section><p className="eyebrow">Deterministic test fixture</p><h2>What the release checks</h2><ul><li><b>Risk route:</b> every fixed case matches its expected route.</li><li><b>Evidence integrity:</b> every cited card exists in the reviewed collection.</li><li><b>Speech guard:</b> elevated-risk results cannot play simulated speech.</li><li><b>Uncertainty:</b> every result states that the interpretation is not verified thought.</li></ul></section><section><p className="eyebrow">DICE: evaluate</p><h2>What caregivers can measure</h2><p>After a routine response, the caregiver can record whether it helped and compare tension before and after. Feedback remains in this browser and is never sent to a model.</p><div className="feedback-summary"><span><b>{helpful}</b> marked helpful</span><span><b>{averageChange.toFixed(1)}</b> average tension change</span></div></section></div>
  <section className="validation-boundary"><strong>Release boundary</strong><p>This dashboard reports deterministic fixture checks and voluntary local feedback. It does not prove treatment effectiveness, diagnose dementia, or replace clinical evaluation.</p></section></section>;
}

export function SettingsPage({ profiles, onCreate, onDelete, onTour, onWelcome, onClear }: { profiles: LocalProfile[]; onCreate: () => void; onDelete: (profile: LocalProfile) => void; onTour: () => void; onWelcome: () => void; onClear: () => void }) {
  const { installable, installed, install } = usePwaInstall();
  return <section className="sub-page"><div className="page-title"><p className="eyebrow">Privacy and preferences</p><h1>Settings</h1></div><div className="settings-grid"><section><h2>Loved one profiles</h2><p>Profiles and photos stay in IndexedDB on this device.</p><button className="button primary" onClick={onCreate}>Create another profile</button>{profiles.map((profile) => <div className="profile-row" key={profile.profileId}><Avatar name={profile.displayName} photo={profile.photoDataUrl} /><div><strong>{profile.displayName}</strong><span>{profile.relationship} · “{profile.preferredName}”</span></div><button className="text-button danger" onClick={() => onDelete(profile)}>Delete</button></div>)}</section><section><h2>Guided introduction</h2><p>Replay the four-step, skippable app tour.</p><button className="button secondary" onClick={onTour}>Replay tour</button><button className="button secondary" onClick={onWelcome}>View welcome page</button></section><section className="danger-zone"><h2>Delete local data</h2><p>Remove profiles, photos, voice preferences, feedback, and scene history from this browser. This cannot be undone.</p><button className="button danger" onClick={onClear}>Delete all local data</button></section><section className="install-card"><h2>Install this PWA</h2>{installed ? <><p className="install-status">✓ Running as an installed app</p><p>This window uses the standalone app experience without the normal browser address bar.</p></> : installable ? <><p>Your browser confirms that this PWA is ready to install.</p><button className="button primary" onClick={() => void install()}>Install app</button></> : <><p>Chrome or Edge: open the browser menu and choose <strong>Install app</strong> or <strong>Add to Home screen</strong>. iPhone Safari: choose <strong>Share → Add to Home Screen</strong>.</p><small>If sideloaded Chrome on a Huawei device does not offer installation, Huawei Browser can still add a home-screen shortcut.</small></>}</section></div></section>;
}
