"use client";

import type { HistoryEntry, KnowledgeCard, KnowledgeSource, LocalProfile } from "../lib/schemas";
import { Avatar } from "./app-ui";

export function HistoryPage({ entries, onOpen, onDelete }: { entries: HistoryEntry[]; onOpen: (entry: HistoryEntry) => void; onDelete: (id: string) => void }) {
  return <section className="sub-page"><div className="page-title"><p className="eyebrow">Stored only in this browser</p><h1>Scene history</h1><p>Reopen a result or remove it at any time.</p></div><div className="history-list">{entries.length === 0 ? <div className="empty-state"><span>◷</span><h2>No saved moments yet.</h2><p>Completed scenes will appear here on this device.</p></div> : entries.map((entry) => <article key={entry.historyId}><div><span className={`risk-dot ${entry.result.riskLevel}`} /> <small>{new Date(entry.createdAt).toLocaleString()}</small><h2>“{entry.input.patientWords}”</h2><p>{entry.result.simulatedWords || entry.result.explanation}</p></div><div><button className="button secondary" onClick={() => onOpen(entry)}>Open</button><button className="text-button danger" onClick={() => onDelete(entry.historyId)}>Delete</button></div></article>)}</div></section>;
}

export function KnowledgePage({ cards, sources }: { cards: readonly KnowledgeCard[]; sources: readonly KnowledgeSource[] }) {
  return <section className="sub-page"><div className="page-title"><p className="eyebrow">Paraphrased and source checked</p><h1>Care knowledge</h1><p>Small, practical cards from authoritative dementia-care sources. They inform Demo and Live AI.</p></div><div className="knowledge-grid">{cards.map((card) => <article key={card.cardId}><span>{card.sceneTags.slice(0, 3).join(" · ")}</span><h2>{card.title}</h2><p>{card.summary}</p><div>{card.sourceIds.map((sourceId) => { const source = sources.find((item) => item.sourceId === sourceId); return source ? <a key={sourceId} href={source.url} target="_blank" rel="noreferrer">{source.organization} ↗</a> : null; })}</div><small>Source checked · {card.reviewedAt}</small></article>)}</div></section>;
}

export function SettingsPage({ profiles, onCreate, onDelete, onTour, onWelcome, onClear }: { profiles: LocalProfile[]; onCreate: () => void; onDelete: (profile: LocalProfile) => void; onTour: () => void; onWelcome: () => void; onClear: () => void }) {
  return <section className="sub-page"><div className="page-title"><p className="eyebrow">Privacy and preferences</p><h1>Settings</h1></div><div className="settings-grid"><section><h2>Loved one profiles</h2><p>Profiles and photos stay in IndexedDB on this device.</p><button className="button primary" onClick={onCreate}>Create another profile</button>{profiles.map((profile) => <div className="profile-row" key={profile.profileId}><Avatar name={profile.displayName} photo={profile.photoDataUrl} /><div><strong>{profile.displayName}</strong><span>{profile.relationship} · “{profile.preferredName}”</span></div><button className="text-button danger" onClick={() => onDelete(profile)}>Delete</button></div>)}</section><section><h2>Guided introduction</h2><p>Replay the four-step, skippable app tour.</p><button className="button secondary" onClick={onTour}>Replay tour</button><button className="button secondary" onClick={onWelcome}>View welcome page</button></section><section className="danger-zone"><h2>Delete local data</h2><p>Remove profiles, photos, voice preferences, and scene history from this browser. This cannot be undone.</p><button className="button danger" onClick={onClear}>Delete all local data</button></section><section><h2>Install this PWA</h2><p>In Chrome or Edge, open the browser menu and choose <strong>Install app</strong>. On iPhone Safari, choose <strong>Share → Add to Home Screen</strong>.</p></section></div></section>;
}
